/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RueckrufRouteImport } from './routes/rueckruf'
import { Route as ProbefahrtRouteImport } from './routes/probefahrt'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as FinanzierungRouteImport } from './routes/finanzierung'
import { Route as FahrzeugeRouteImport } from './routes/fahrzeuge'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AutoVerkaufenRouteImport } from './routes/auto-verkaufen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FahrzeugeIdRouteImport } from './routes/fahrzeuge.$id'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RueckrufRoute = RueckrufRouteImport.update({
  id: '/rueckruf',
  path: '/rueckruf',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbefahrtRoute = ProbefahrtRouteImport.update({
  id: '/probefahrt',
  path: '/probefahrt',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzierungRoute = FinanzierungRouteImport.update({
  id: '/finanzierung',
  path: '/finanzierung',
  getParentRoute: () => rootRouteImport,
} as any)
const FahrzeugeRoute = FahrzeugeRouteImport.update({
  id: '/fahrzeuge',
  path: '/fahrzeuge',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoVerkaufenRoute = AutoVerkaufenRouteImport.update({
  id: '/auto-verkaufen',
  path: '/auto-verkaufen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FahrzeugeIdRoute = FahrzeugeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FahrzeugeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auto-verkaufen': typeof AutoVerkaufenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fahrzeuge': typeof FahrzeugeRouteWithChildren
  '/finanzierung': typeof FinanzierungRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/probefahrt': typeof ProbefahrtRoute
  '/rueckruf': typeof RueckrufRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/fahrzeuge/$id': typeof FahrzeugeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auto-verkaufen': typeof AutoVerkaufenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fahrzeuge': typeof FahrzeugeRouteWithChildren
  '/finanzierung': typeof FinanzierungRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/probefahrt': typeof ProbefahrtRoute
  '/rueckruf': typeof RueckrufRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/fahrzeuge/$id': typeof FahrzeugeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auto-verkaufen': typeof AutoVerkaufenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fahrzeuge': typeof FahrzeugeRouteWithChildren
  '/finanzierung': typeof FinanzierungRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/probefahrt': typeof ProbefahrtRoute
  '/rueckruf': typeof RueckrufRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/fahrzeuge/$id': typeof FahrzeugeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auto-verkaufen'
    | '/datenschutz'
    | '/fahrzeuge'
    | '/finanzierung'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/probefahrt'
    | '/rueckruf'
    | '/sitemap.xml'
    | '/ueber-uns'
    | '/fahrzeuge/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auto-verkaufen'
    | '/datenschutz'
    | '/fahrzeuge'
    | '/finanzierung'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/probefahrt'
    | '/rueckruf'
    | '/sitemap.xml'
    | '/ueber-uns'
    | '/fahrzeuge/$id'
  id:
    | '__root__'
    | '/'
    | '/auto-verkaufen'
    | '/datenschutz'
    | '/fahrzeuge'
    | '/finanzierung'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/probefahrt'
    | '/rueckruf'
    | '/sitemap.xml'
    | '/ueber-uns'
    | '/fahrzeuge/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoVerkaufenRoute: typeof AutoVerkaufenRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FahrzeugeRoute: typeof FahrzeugeRouteWithChildren
  FinanzierungRoute: typeof FinanzierungRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  ProbefahrtRoute: typeof ProbefahrtRoute
  RueckrufRoute: typeof RueckrufRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UeberUnsRoute: typeof UeberUnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rueckruf': {
      id: '/rueckruf'
      path: '/rueckruf'
      fullPath: '/rueckruf'
      preLoaderRoute: typeof RueckrufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probefahrt': {
      id: '/probefahrt'
      path: '/probefahrt'
      fullPath: '/probefahrt'
      preLoaderRoute: typeof ProbefahrtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzierung': {
      id: '/finanzierung'
      path: '/finanzierung'
      fullPath: '/finanzierung'
      preLoaderRoute: typeof FinanzierungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fahrzeuge': {
      id: '/fahrzeuge'
      path: '/fahrzeuge'
      fullPath: '/fahrzeuge'
      preLoaderRoute: typeof FahrzeugeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-verkaufen': {
      id: '/auto-verkaufen'
      path: '/auto-verkaufen'
      fullPath: '/auto-verkaufen'
      preLoaderRoute: typeof AutoVerkaufenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fahrzeuge/$id': {
      id: '/fahrzeuge/$id'
      path: '/$id'
      fullPath: '/fahrzeuge/$id'
      preLoaderRoute: typeof FahrzeugeIdRouteImport
      parentRoute: typeof FahrzeugeRoute
    }
  }
}

interface FahrzeugeRouteChildren {
  FahrzeugeIdRoute: typeof FahrzeugeIdRoute
}

const FahrzeugeRouteChildren: FahrzeugeRouteChildren = {
  FahrzeugeIdRoute: FahrzeugeIdRoute,
}

const FahrzeugeRouteWithChildren = FahrzeugeRoute._addFileChildren(
  FahrzeugeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoVerkaufenRoute: AutoVerkaufenRoute,
  DatenschutzRoute: DatenschutzRoute,
  FahrzeugeRoute: FahrzeugeRouteWithChildren,
  FinanzierungRoute: FinanzierungRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  ProbefahrtRoute: ProbefahrtRoute,
  RueckrufRoute: RueckrufRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UeberUnsRoute: UeberUnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
